### ISSUE TITLE
There is absolutely no guide on updating the server

### ISSUE THREAD

**Issue by DBTDerpbox** [DBTDerpbox/Legacy-Edition-Battle#18]
Currently, updating the server is done via deleting the entire world folder excluding advancements and redownloading the source from github and copying everything excluding advancements back into the world folder

a proper guide needs to be made about this

**Comment by PiporGames** [comment]
Maybe an auto-update script could be added

**Comment by DBTDerpbox** [comment]
would would you handle that?
like upon launch of LEB?

**Comment by PiporGames** [comment]
I will try my best, altough I don't really know that much at python. As for Windows, I can  try to add a GUI aswell, .Net Framework is already part of the Windows 10 Core so I can work without any dependencies.

**Comment by DBTDerpbox** [comment]
a thing to consider is dedicated servers (which LEB public also runs on) most of the time run some form of Linux, and many hosts do not support supplying launching a .py file instead of .jar

**Comment by DBTDerpbox** [comment]
i'm willing to make an updater when i figure out how to take an existing file and rewrite parts of it in python (which is also why LEB-Modloader is completely stuck again)

**Comment by PiporGames** [comment]
I tought the updater objective was to replace the old files with new ones, not rewriting parts of the files itself.

**Comment by DBTDerpbox** [comment]
well thats *mostly* its job, but also updating the MOTD to display the correct commit

**Comment by PiporGames** [comment]
Don't worry about It, feel free to focus on other things. I'll make the program when I finish some stuff I have to do.

**Comment by DBTDerpbox** [comment]
i see
MOTDs arent the most important thing, i actually dont think public LEB's MOTD is on this repo or anywhere else

do you need it?

**Comment by PiporGames** [comment]
Yes. Besides the MOTD, does the program need to do anything else?

**Comment by DBTDerpbox** [comment]
pretty much no, maybe the ability to select what branch to download from? might be complicated to add and honestly not worth it since main is the only branch that receives updates at all

**Comment by PiporGames** [comment]
GUIs and branch selector is done. What files do you want to backup?

**Comment by DBTDerpbox** [comment]
the `advancements` folder inside of the world folder, the only thing you'll be replacing is the world folder itself and the SRP config in `config/switchableresourcepacksconfig.json5`

**Comment by DBTDerpbox** [comment]
this has been solved with the existence of LEB-ToolBox being used for updates now
