### ISSUE TITLE
Merge install.py and update.py into one file

### ISSUE THREAD

**Issue by PiporGames** [DBTDerpbox/Legacy-Edition-Battle#19]
Mixing the two files into one .py file is easier to use for end user, compacts every external tool for LEB in one spot, and it takes advantages of the update.py GUI.

**Comment by DBTDerpbox** [comment]
i am completely all for this, the current installer can be confusing to a lot of people, a far better user interface would definitely make it easier to use, and the ability to update from right inside the installer itself.

once the updater is considered stable, this should probably be done

**Comment by PiporGames** [comment]
update.py pull request will be freezed until I finish porting the install.py code and applying the necesary GUI tweaks.
currently, porting the code. GUI is 50% done.
