### ISSUE TITLE
server.properties missing arguments

### ISSUE THREAD

**Issue by PiporGames** [DBTDerpbox/Legacy-Edition-Battle#23]
It would be helpful if you could add the following lines, and every other config missing from the current LEB official server.
for example:
resource-pack=https://dbtderpbox.github.io/LEB-Resources/zip/resources1.zip
resource-pack-prompt=Legacy Edition Battle requires a resource pack to function properly!

... and every other thing needed for LEB to work as intended.

This lines MUST be added above the motd line, meaning that the motd should always be the last one of the list.
This is for easier managing at the update.py file.

**Comment by DBTDerpbox** [comment]
that option isnt even used anymore, actually enabling it would cause issues with the current resource loader

if you're looking for where the resource config is, check `config/switchableresourcepacks.json5`

**Comment by PiporGames** [comment]
So, the server.properties at github is enough for it to work as intended? In that case, close the incident (sorry for opening in the first place)

**Comment by DBTDerpbox** [comment]
yes, its enough, *as long as you have the dependencies installed*
