### ISSUE TITLE
texts that need to be turned into translation keys

### ISSUE THREAD

**Issue by DBTDerpbox** [DBTDerpbox/Legacy-Edition-Battle#27]
This will contain a list of everything that needs to be turned into translation keys
**Note:** *This excludes host menus! Those will be dealt with eventually.*

*Nothing is here currently!*

Think you've found something? Send a comment showing what file and line the text is on.

**Comment by PiporGames** [comment]
I don't understand, you mean that text needs to be translated, or that it needs to be converted to a trans key inside leb's core?

**Comment by DBTDerpbox** [comment]
both, it needs to be turned into a translation key in LEB-Resources and also translated

**Comment by PiporGames** [comment]
If I knew how to properly add the trans keys, I would help you

**Comment by DBTDerpbox** [comment]
the biggest issue really is this requires a resource update which i only want to do every so often due to redownloading

**Comment by PiporGames** [comment]
I'll take a look into this

**Comment by DBTDerpbox** [comment]
merged to testing, clearing the list above

**Comment by DBTDerpbox** [comment]
i'll keep the issue open for whenever new keys end up getting added

**Comment by DBTDerpbox** [comment]
Closing this as i'll start adding keys to the resource-update branch when needed
