### ISSUE TITLE
OOB Barrier is too strict

### ISSUE THREAD

**Issue by NoahTheNerd** [DBTDerpbox/Legacy-Edition-Battle#31]
On maps like the castle courtyard one (forgot the name, sorry Emmie) its impossible to climb some ladders due to the anti oob barrier.

**Comment by DBTDerpbox** [comment]
this is fixed for castle in testing, but i have now found a new one in atomics

**Comment by DBTDerpbox** [comment]
currently in testing, both of these issues are fixed, feel free to re-open this issue if you find something
