### ISSUE TITLE
Custom Map Support

### ISSUE THREAD

**Issue by Gota7** [DBTDerpbox/Legacy-Edition-Battle#34]
Hey, great work on this project, my brother and I love playing it!

Is there plans to allow for custom maps for battles and hubs? We would like to create custom maps to play on. I do have plenty of programming experience, so I could implement such additions myself if given the proper places to look and make a PR.

**Comment by PiporGames** [comment]
(Not the actual author of LEB, but might help)
Hi, and thanks for taking interest on LEB remake. We don't currently support the mods and tools required to do custom maps (only to set the required components to work, but not the ones needed to test it). This will make testing your map quite hard, as it needs to be compiled internally on our side (Derpbox should know how) to be played. You can submit your own maps to our discord (ask Derpbox), but we cannot guarantee how long the process will take, as again, we currently lack any automatic compilers nor tools, so we need to setup each map by hand. I hope this might clear things up. I would suggest talking to the creator for further details.

**Comment by PiporGames** [comment]
Basically, custom map support is an upcoming feature, but we currently lack the 'proper' tools to make them. We have been accepting for now only remastered editions of legacy maps.

**Comment by Gota7** [comment]
Could I have a link to this discord server? (Gota7#6587)

**Comment by DBTDerpbox** [comment]
> Could I have a link to this discord server? (Gota7#6587)

https://discord.gg/KHXzrQ3r

**Comment by DBTDerpbox** [comment]
Regarding custom map support, its similar to what pipor said

currently the tools to *build* these maps in-game exist, but not the tools required to load them in the actual LEB server exist *yet*

I want to get around to it soon, but i've been really busy recently

**Comment by DBTDerpbox** [comment]
On the note of this, i've been working on this feature for the past few days and i've posted progress [here](https://www.youtube.com/watch?v=6engp5EE9kI).

**Comment by DBTDerpbox** [comment]
Should note, this feature is being tested on the public server currently

**Comment by DBTDerpbox** [comment]
closing this issue, as this feature is now a thing properly

for info on how to make a map, see the [ModTools Documentation](https://github.com/DBTDerpbox/LEB-ModTools/wiki)
