### ISSUE TITLE
Wont let me extract the zip file

### ISSUE THREAD

**Issue by RandomCakes** [DBTDerpbox/Legacy-Edition-Battle#35]
Currently I'm using winrar, and it won't let me extract the file due to it being, "corrupt." I've tried extracting it on both minehut and on file explorer.

**Comment by DBTDerpbox** [comment]
Thats strange, theres a chance it actually is and something went wrong with the download, have you tried the build in windows zip extractor?

**Comment by DBTDerpbox** [comment]
Closed due to inactivity
