### ISSUE TITLE
weird text 

### ISSUE THREAD

**Issue by SiDjackWasTaken** [DBTDerpbox/Legacy-Edition-Battle#36]
weird text only happens on leb

![image](https://user-images.githubusercontent.com/98195044/183244320-33156a1e-a861-4062-a6b2-e6176d237f93.png)

**Comment by DBTDerpbox** [comment]
Interesting, this doesnt happen for me, what mods and resource packs are you using?

**Comment by SiDjackWasTaken** [comment]
![Screenshot 2022-08-06 202335](https://user-images.githubusercontent.com/98195044/183244978-2896025d-1d18-4cde-b29c-8bcb1fcea489.png)
![Screenshot 2022-08-06 202409](https://user-images.githubusercontent.com/98195044/183244983-4da3f642-6d5f-4198-a469-192f65a6f0a9.png)
![Screenshot 2022-08-06 202443](https://user-images.githubusercontent.com/98195044/183244989-c8a9df20-af48-4fb2-a50c-36e67419af61.png)

**Comment by SiDjackWasTaken** [comment]
turned off the packs works now

**Comment by DBTDerpbox** [comment]
theres likely a pack that breaks my custom UI font stuff

**Comment by DBTDerpbox** [comment]
why was this reopened?

**Comment by SUPERN00Bthefirst** [comment]
Do you have Force Unicode enabled?
