### ISSUE TITLE
failed to load funtion

### ISSUE THREAD

**Issue by redmine4404** [DBTDerpbox/Legacy-Edition-Battle#51]
i want to solf host a LEM server for me and my friends.

The problem is i spawn in a little house with a bookshelf saying :  this is where all containers required  for MCF jank is stored [...] your spawnpoint is probably broken and the respawn script did not run properly.

![2023-09-16_19 10 44](https://github.com/Legacy-Edition-Minigames/Minigames/assets/96315018/123490ce-1337-4cdf-8a26-9a2ef3832e3c)
![2023-09-16_19 10 47](https://github.com/Legacy-Edition-Minigames/Minigames/assets/96315018/081b2233-5d78-47f5-be33-cdc0395aa494)

**Comment by redmine4404** [comment]
i think it's related to the hundred of error "Failed to load function error".

there is the log : 
[2023-09-16-6.log](https://github.com/Legacy-Edition-Minigames/Minigames/files/12641259/2023-09-16-6.log)

**Comment by redmine4404** [comment]
i think it's a depency issue or a register issue (or i'm just stupid and i have mess up some thing).
I don't know how data packs work so i can't do affirmation.
Thank you in advance for your help

**Comment by S-N00B-1** [comment]
Hello, Self hosting currently isn't fully supported. In order to install a server it is recommended that you use [toolbox.](https://github.com/Legacy-Edition-Minigames/ToolBox/tree/java)
It is undergoing a full rewrite right now, so some things may not work as intended.

**Comment by DBTDerpbox** [comment]
As mentioned by S_N00B, ToolBox is currently not in a fully usable state, you're free to try to use it but don't expect a very stable experience at the moment.
