### ISSUE TITLE
Me and my friend built the server with the files supplied 

### ISSUE THREAD

**Issue by AdroitJackson** [DBTDerpbox/Legacy-Edition-Battle#57]
So we built the server using this GitHub and upon entering Everything works but when waiting out the start timer or readying up it doesn't work or goes in the negatives. we didn't install the extra resources so is it to do with that or something else entirely? Fyi the server is running on Linux mint if it helps.

**Comment by DBTDerpbox** [comment]
did you not use toolbox for this?

**Comment by AdroitJackson** [comment]
@DBTDerpbox is tool box a that a mod we missed because we have everything else?   Ya know like via fabric ect-  if so can I find it on fabric or forge

**Comment by DBTDerpbox** [comment]
LEM ToolBox is a tool to set up LEM servers and is the intended way to self host them

You can find it's repo in this organization, make sure to get toolbox 2.0 from releases, not toolbox 1.6

**Comment by AdroitJackson** [comment]
@DBTDerpbox thanks 🙏 so as a check you don't care if people re build you server to play it correct? I'll probably come back if something goes wrong btw.

**Comment by DBTDerpbox** [comment]
Go ahead, keep in mind this project is unfinished still and you might run into issues

just don't claim you made it

**Comment by AdroitJackson** [comment]
Kk thanks again

**Comment by AdroitJackson** [comment]
@DBTDerpbox you guys have a discord

**Comment by DBTDerpbox** [comment]
We do, but it requires a whitelisted account to be able to talk

**Comment by AdroitJackson** [comment]
Ah
