### ISSUE TITLE
Plans for Glide?

### ISSUE THREAD

**Issue by raikasdev** [DBTDerpbox/Legacy-Edition-Battle#58]
Hi! I was also thinking of creating a project like this few years back and got interested with Legacy4J project and discovered this. Do you have any plans for implementing the Glide minigame at some point?

Personally liked it a lot. I'm a Minecraft developer myself doing very customized things with resource packs and stuff like this, but I do all stuff with Paper and Java so my skillset probably wouldn't be that useful as y'all use data packs :thinking: 

If y'all aren't planning this I might as well just try implementing something like that with Java at some point. Quite busy right now but maybe in the future.

**Comment by DBTDerpbox** [comment]
we have been working on it for a while, check the last few progress updates on our youtube channel

**Comment by DBTDerpbox** [comment]
it should also be said, we are in the process of moving all the remaining datapack code over to fabric

**Comment by raikasdev** [comment]
Great, just saw that the one mod said that only Battle is supported with Tumble in the works :)
