### ISSUE TITLE
New Discord link please :)

### ISSUE THREAD

**Issue by OCsonic** [DBTDerpbox/Legacy-Edition-Battle#60]
My discord is `ocsonic` if you could dm it to me! I really want to follow the development (plus the devs here seem super chill which is always a plus)

**Comment by S-N00B-1** [comment]
The discord is intended for Whitelist members, you can still join it, but you will be unable to talk in any of the channels.

**Comment by OCsonic** [comment]
I can't find any valid links to the discord

**Comment by DBTDerpbox** [comment]
If you aren't whitelisted, you won't be able to talk, are you ok with this?

**Comment by OCsonic** [comment]
yeah that's perfectly fine to me

**Comment by DBTDerpbox** [comment]
https://discord.gg/PJMta9Ga
