### ISSUE TITLE
Is it possible to add a gliding minigame?

### ISSUE THREAD

**Issue by lavabyte** [DBTDerpbox/Legacy-Edition-Battle#61]
Is it possible to add a gliding minigame?

**Comment by DBTDerpbox** [comment]
This is being worked on, you can find updates on this usually in our [Progress Updates](https://www.youtube.com/playlist?list=PLtHQsKobsxzbW6f5uStXNY2PIz03cRtDo)

You can also see some of the recent rendering work S_N00B has been doing [here](https://www.youtube.com/watch?v=7zVpyDlgEE4)
