### ISSUE TITLE
Can someone please make or provide a guide on how I can build and host this myself

### ISSUE THREAD

**Issue by Telarmine2** [DBTDerpbox/Legacy-Edition-Battle#62]
Title, I think this is a very cool project and me and my friends would love to play these mingames in an updated format. However, I cannot figure out how to download and build this so that I can run it. Every time I have tried it has just resulted in lots of errors that me and Chat GPT cannot figure out. Thank you in advance

**Comment by S-N00B-1** [comment]
Toolbox is the intended method for self-hosted lem servers.
https://github.com/Legacy-Edition-Minigames/ToolBox/releases/tag/2.0.0

**Comment by Telarmine2** [comment]
Amazing. Thank you for the tip. I'm guessing there's no way to get any gamemode aside from battle yet?

**Comment by S-N00B-1** [comment]
The other minigames are still in development.
